server:
  port: 8082

spring:
  application:
    name: nexa-auth
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/nexa_task?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update